apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-ingress
spec:
  tls:
    - hosts:
        - {{nip}}
      secretName: ingress-tls
  rules:
  - host: {{nip}}
    http:
      paths:
      - path: /
        backend:
          service:
            name: sample-deploy
            port:
              number: 80
        pathType: ImplementationSpecific